# Continuous Delivery via GitHub Actions.

name: Continuous Delivery

on:
  push:
    branches:
      - master

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip') && !contains(github.event.head_commit.message, 'skip ci')"
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Cache Node Modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: npm-${{ hashFiles('**/package-lock.json') }}

      - name: Install Dependencies
        run: npm ci

      - name: Link Local Packages
        run: npm run bootstrap

      - name: Build
        run: npm run build

      - name: Version
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        run: npm run version

      - name: Configure CI Git User
        run: |
          git config --global user.email andy.bettisworth@gmail.com
          git config --global user.name Andy Bettisworth

      - name: Publish
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        run: npm run publish

  gh-pages:
    name: Github Pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Cache Node Modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: npm-${{ hashFiles('**/package-lock.json') }}

      - name: Install Dependencies
        run: npm ci

      - name: Publish
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        run: npm run deploy-storybook -- --ci
        env:
          GH_TOKEN: ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}
